### ISSUE TITLE
We need a dank favicon

### ISSUE THREAD

**Issue by almiche** [famingolabs/famingolabs#7]

**Comment by kcamcam** [comment]
agreed, im gonna whip something up quick

**Comment by kcamcam** [comment]
![flamingo](https://user-images.githubusercontent.com/16027312/35373368-185a3592-016c-11e8-9758-2cd31ac8047f.png)

Need to add a references to the "author" if we use it
<div>Icons made by <a href="https://www.flaticon.com/authors/pixel-perfect" title="Pixel perfect">Pixel perfect</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>

**Comment by kcamcam** [comment]
![flamingo](https://user-images.githubusercontent.com/16027312/35373589-272e98fa-016d-11e8-9f98-94a5a9b9eef4.png)
